name: MERN CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  backend:
    name: Backend
    runs-on: self-hosted
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install backend dependencies
        run: npm install

      - name: Run backend tests
        run: npm test || echo "⚠️ No backend tests defined"

  frontend:
    name: Frontend
    runs-on: self-hosted
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install frontend dependencies & build
        run: |
          npm install
          npm run build

