name: MERN CI Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  backend:
    name: Backend
    runs-on: self-hosted
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: npm install

      - name: Run backend tests
        run: npm test || echo "⚠️ No backend tests defined"

  frontend:
    name: Frontend
    runs-on: self-hosted
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build
